session_name: Personal
windows:
  - window_name: one
    panes:
      -
  - window_name: System Status
    layout: main-vertical
    panes:
      - 
      - shell_command_before: set_title "htop, currently running processes" && clear
        shell_command: nix-shell -p gotop --run gotop
